# Generated by Django 5.0.6 on 2024-05-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UHN", "0003_rename_prediction_testfile_prediction_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testfile",
            name="image",
            field=models.ImageField(upload_to="UHN/data"),
        ),
        migrations.AlterField(
            model_name="testfile",
            name="uploaded_at",
            field=models.DateTimeField(),
        ),
    ]
