# Generated by Django 5.0.6 on 2024-05-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UHN", "0004_alter_testfile_image_alter_testfile_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testfile",
            name="image",
            field=models.FileField(upload_to="UHN/data/pred_img/"),
        ),
    ]
