# Generated by Django 5.0.6 on 2024-05-31 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UHN", "0005_alter_testfile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testfile",
            name="image",
        ),
    ]
